CREATE TABLE IF NOT EXISTS managedOwnerRegistration (
    managedOwnerRegistrationId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    installationUuid CHAR(36) NOT NULL,
    firstRegistered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastRegistered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ownerName VARCHAR(255) NOT NULL,
    ownerEmail VARCHAR(255) NOT NULL,
    ownerPhone VARCHAR(64) NOT NULL,
    ownerAddress VARCHAR(500) NOT NULL,
    siteName VARCHAR(255) NULL,
    siteAddress VARCHAR(500) NULL,
    country CHAR(2) NULL,
    hostname VARCHAR(255) NULL,
    machineId VARCHAR(128) NULL,
    sourceInstallationId BIGINT UNSIGNED NULL,
    paymentAvailable BIT(1) NOT NULL DEFAULT b'0',
    followUpStatus ENUM('new','contacted','onboarding','active','not_interested','invalid') NOT NULL DEFAULT 'new',
    followUpTime TIMESTAMP NULL,
    followUpNote TEXT NULL,
    PRIMARY KEY (managedOwnerRegistrationId),
    UNIQUE KEY uq_global_installation_uuid(installationUuid),
    KEY idx_global_owner_email(ownerEmail),
    KEY idx_global_owner_phone(ownerPhone),
    KEY idx_global_country(country),
    KEY idx_global_followup(followUpStatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
