CREATE TABLE IF NOT EXISTS payment (
    paymentId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    provider VARCHAR(32) NOT NULL,
    providerRequestId VARCHAR(96) NOT NULL,
    providerPaymentId VARCHAR(128) NULL,
    planId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NULL,
    phone VARCHAR(64) NULL,
    email VARCHAR(255) NULL,
    clientIp VARCHAR(45) NULL,
    currency CHAR(3) NOT NULL,
    amountMinor BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    paidTime TIMESTAMP NULL,
    activatedTime TIMESTAMP NULL,
    failureReason VARCHAR(255) NULL,
    providerPayload LONGTEXT NULL,
    PRIMARY KEY(paymentId),
    UNIQUE KEY uq_payment_request(provider, providerRequestId),
    KEY idx_payment_provider_id(provider, providerPaymentId),
    KEY idx_payment_status(status),
    KEY idx_payment_user(userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
