PACKAGE_NAME="tarakernel"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="tarakernel"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make -j1 KVER=${kernelver}"
CLEAN="make KVER=${kernelver} clean"
