# diagnose.template.conf
# Modify and save this file as ~/diagnose.conf

nodes = 10.100.0.1,10.47.10.1,10.47.10.2
# what user name to use in ssh test on IPs above. Leave untouched to drop ssh test
ssh_targets = user1@<ip_to_reach_node1_directly>,user2@<ip_to_reach_node2_directly>

# Optional. If empty/missing, script tries to detect it from nodes.
my_ip = 10.47.10.2

# Should contain "client" or "host" (determins how firewall should be set up)
ssh_mode = client