# --------------------------------------------------
# Taransvar VPS IPsec Hub Configuration
# --------------------------------------------------

#Fill in your details below and save as /root/taransvar/vpn_vps.conf
#Then run sudo perl ~/taransvar/tool/vpn_vps.pl (or wherever you put the git) to run it.

#Assign a VPN IP address if you like. Otherwise it still has its public IP. Any IP is ok, our standard is: 
VPN_VPS_IP=10.<courntryId>.0.1  or 10.<courntryId>.<partnerid>.0

# Public/WAN interface on this VPS
VPS_WAN_IF=enp1s0

# Public IP address of this VPS
VPS_PUBLIC_IP=YOUR_VPS_PUBLIC_IP

# Local network(s) reachable behind the VPS.
# For now, keep this broad if the VPS is acting as a hub for the Taransvar overlay.
CORE_LOCAL_SUBNET=10.0.0.0/8


# --------------------------------------------------
# Site 1
# --------------------------------------------------

SITE1_NAME=SITE1_NAME
SITE1_REMOTE_ID=any
SITE1_PSK=REPLACE_WITH_UNIQUE_SHARED_SECRET
SITE1_REMOTE_SUBNET=10.<countryId>.<partnerId>.0/24


# --------------------------------------------------
# Site 2
# --------------------------------------------------

#SITE2_NAME=SITE2_NAME
#SITE2_REMOTE_ID=any
#SITE2_PSK=REPLACE_WITH_UNIQUE_SHARED_SECRET
#SITE2_REMOTE_SUBNET=10.<countryId>.<partnerId>.0/24


# --------------------------------------------------
# Site 3
# --------------------------------------------------

#SITE3_NAME=SITE3_NAME
#SITE3_REMOTE_ID=any
#SITE3_PSK=REPLACE_WITH_UNIQUE_SHARED_SECRET
#SITE3_REMOTE_SUBNET=10.<countryId>.<partnerId>.0/24