# Taransvar VPS IPsec hub configuration
# Save as /root/taransvar/vpn.conf on the VPS
# Or call the script with conf file name as parameter.

#ROLE=[vps|peer] - "vps" can be any kind of node with public IP address. "peers"s connect to a "vps"
ROLE=vps

VPN_VPS_IP=10.47.0.1
VPS_WAN_IF=enp1s0
VPS_PUBLIC_IP=81.88.19.252

# The VPS itself for now. Use 10.0.0.0/8 later for broad overlay hub routing.
CORE_LOCAL_SUBNET=10.47.0.1/32

SITE1_NAME=torsas_ipsec
SITE1_REMOTE_ID=torsas_ipsec
SITE1_PSK=PUT_SAME_LONG_SECRET_AS_ON_PEER_HERE
SITE1_REMOTE_SUBNET=10.47.199.1/32
